---
name: main

on: [push]

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: bash install.sh
      - name: print .zshrc
        run: cat ~/.zshrc
      - name: load .zshrc
        shell: zsh {0}
        run: |
          source ~/.zshrc
          la